### ISSUE TITLE
v4.1.0 breaks the compatibility with jupyterlab 1.x

### ISSUE THREAD

**Issue by trungleduc** [fcollonval/jupyterlab_toastify#8]
Hi Frederic,
I updated ` jupyterlab_toastify` from v4.0.0 to v4.1.0 and then my extension for jupyterlab 1.2.6 has stopped working. I got following error while rebuilding jupyterlab: 
```
./node_modules/jupyterlab_toastify/lib/ToastJupyterLab.js 209:28-37
    "export 'closeIcon' was not found in '@jupyterlab/ui-components'

jupyter-project 1.0.1
jupyterlab_toastify 4.1.0
@jupyterlab/ui-components 1.2.1 
```
My project depends on `jupyterlab_toastify` indirectly through `jupyter-project`, so i can not force jupyterlab to use v4.0.0.
Thanks for you help.
Trung

**Comment by fcollonval** [comment]
Thanks for reporting @trungleduc 

#9 should fix it. Let me know if it works with 4.1.1

**Comment by trungleduc** [comment]
Yes, it works. Thank you @fcollonval
